#!/usr/bin/env python3
import os

os.system('rm -f country_data/*.csv')
os.system('rm -f country_data/*.json')
os.system('rm -f outputs/*.csv')
os.system('rm -f plots/*.png')

os.system('./process_covid_data.py')
os.system('./run_analysis.py')
os.system('./plot_csv.py')
